### ISSUE TITLE
[Molecule] Build Graduates/Volunteer Profile Layout.

### ISSUE THREAD

**Issue by UmmuAyyub** [team-refcode/refcode.org#120]
following the casamarianella site, build graduates/volunteers profile.
http://www.casamarianella.org/about-us/casa-staff/

![Screen Shot 2019-08-16 at 5 44 02 PM](https://user-images.githubusercontent.com/29615921/63200110-05df1980-c04e-11e9-90d5-74dbda02ee78.png)

**Comment by MustafaAlsaeedi** [comment]
Again, this has as same layout as one of the previous tasks here: #86 @UmmuAyyub
