### ISSUE TITLE
Create Figma Design for Graduates section

### ISSUE THREAD

**Issue by brentonstrine** [team-refcode/refcode.org#176]
We need a design for our section that showcases all of the graduates from each cohort. 

Design requirements:

1. Needs to match the "look and feel" of the rest of the website. Use [Brenton's Figma design](https://www.figma.com/file/diPDYDpszJKzB0idY0Ar9N/Refcode-2.0-Website?node-id=0%3A1) and the [Casa Marianella](https://www.casamarianella.org/) website as a reference for the style. 
2. Look at our [existing pages](https://master--refcode.netlify.app/graduates-fall-2019.html) as a reference as well. Your design doesn't have to be the same though.
3. Each cohort should have it's own page which will feature a group photo of the whole cohort as  well as individual photos for each graduate. 
4. Each graduate will have a photo, their name, and links to their GitHub, Website, and LinkedIn.

When the Figma is complete, attach a link to this issue and we will do a design review together.

**Comment by ayabaknu** [comment]
figma design for Graduates page
![Uploading refcode.png…]()

[a link](https://www.figma.com/file/epwKfd5aFHyNNMcqv34Slg/refcode?node-id=25%3A0)

**Comment by ayabaknu** [comment]
![refcode](https://user-images.githubusercontent.com/48158451/97317947-be534080-1841-11eb-9971-5a335ceb0079.png)

**Comment by ayabaknu** [comment]
https://www.figma.com/file/epwKfd5aFHyNNMcqv34Slg/refcode?node-id=25%3A0

**Comment by brentonstrine** [comment]
@ayabaknu These are really great designs! You clearly put a lot of work into them! I have a few pieces of feedback that I want to give you. 

Could you change the figma so that I can leave a comment on it? I think you can change that by clickgin the "share" button in the rop right and changing my permissions:
![image](https://user-images.githubusercontent.com/1900802/97347256-e7d09400-1862-11eb-8e9f-f0b257d87460.png)
