### ISSUE TITLE
Decide Site map

### ISSUE THREAD

**Issue by brentonstrine** [team-refcode/refcode.org#77]
Ideas for what pages should be on the site? here’s what we currently have:

- About
- Apply
- Graduates
- Curriculum
- Volunteer
- Teamcode
- Contact

**Comment by MustafaAlsaeedi** [comment]
We can start with what we currently have and take into consideration subsites for each page in the navigation.

1. Graduation page: subsites for each graduation year.
2. About us page: subsites  A. refcde B. friends of refugees C. Mission & vission statements. etc.
3. Contact (Request More Information) - subsites A. Volunteers B. Donation

**Comment by 24sint** [comment]
Here is some of the points what I have about the site map.
1. Remove the apply.html file and make together with the contact.html file
2. Rename the About Refcode to Home page or from Mustefa's suggestions 
3. Join the curriculum.html file ( the general information about the courses) make together with the About Refcode (Home) page
4. How can we address or ask companies, organization, and others to give the chance for the graduates to upgrade their knowledge or to practice? May be in the volunteers page.... ???

**Comment by ttkethiopia** [comment]
it looks good for me if we use the same navigation list as listed above (About, Apply,Graduates, Curriculum,Volunteer,Teamcode,Contact). as mustafa said, it is also a good idea if the lists have subsites. i also agree with sintu on changing the name about refcode to home page or just about.

**Comment by MustafaAlsaeedi** [comment]
Sintu, Tariku, and I are finalizing the map to complete the project, please let us know if you have any question or would like to add/change anything on the site map.

Home | contain curriculum information and what we offer
About us | background information, staff, volunteers, team code etc
Graduates | list of graduated students
Services | what can we offer to companies and communities
Contact us | contact us form
