### ISSUE TITLE
Build pattern library

### ISSUE THREAD

**Issue by brentonstrine** [team-refcode/refcode.org#93]
The pattern library is a mini website that contains all of the different components (Atoms, Molecules, Organisms and maybe even Templates) that can be used in the site.

Then when developers are building pages, we can go to the pattern library to use the pattern as needed. 

Whenever a new component is built, it should also be added to the pattern library.

Pattern library (for now) can be a page with the following sections (to be added as we build components):
```

H1 Pattern Library

<NAV> (links to sections below)

<SECTION>
H2 Atoms
- atoms
- go
- here

<SECTION>
H2 Molecules
- molecules
- go
- here

<SECTION>
H2 Organisms
- organisms
- go
- here

<SECTION>
H2 Templates
- templates
- go
- here


```

**Comment by brentonstrine2** [comment]
I created PR https://github.com/team-refcode/refcode.org/pull/94 which solves this.
